- name: Setup Docker on new VM
  hosts: vm
  connection: ssh
  become: true
  gather_facts: false

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: true

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true
